---
title: "tp7-Parte-b"
author: "Gaston Cavallo"
date: "27/10/2021"
output: html_document
---

```{r setup, include=FALSE}
#cargar librerias
library(dplyr) 
library(readr)
library(rpart)
library(caret)
library(randomForest)

```

```{r, include=FALSE}
#cargar dataset

#set.seed(123)
dataset <- read_csv("arbolado-mza-dataset.csv")
testset <- read_csv("arbolado-mza-dataset-test.csv")

```


```{r}
#cortamos el dataset 
dataset$inclinacion_peligrosa <- as.factor(dataset$inclinacion_peligrosa)
dataset$especie <- as.factor(dataset$especie)
#dataset$altura <- as.factor(dataset$altura)
testset$especie <- as.factor(testset$especie)
#testset$altura <- as.factor(testset$altura)
#trainIdx <- createDataPartition(as.factor(dataset$inclinacion_peligrosa),p=0.80,list=FALSE)
#trainData <- dataset[ trainIdx, ]
#testData <- dataset[ -trainIdx, ]
#
#trainData
#testData
#testset
```

```{r}
#visualizar los datos por columna
#summary(trainData)
sapply(dataset, class)
#sapply(trainData, class)

#summary(testData)
#sapply(testData, class)


#summary(testset)
sapply(testset, class)
```


```{r}
# Save trees ID
treesID <- testset$id

drop <- names(dataset) %in% c("ultima_modificacion")
dataset <- dataset[,!drop]

drop <- names(dataset) %in% c("lat")
dataset <- dataset[,!drop]

drop <- names(dataset) %in% c("long")
dataset <- dataset[,!drop]

drop <- names(dataset) %in% c("nombre_seccion")
dataset <- dataset[,!drop]

drop <- names(dataset) %in% c("seccion")
dataset <- dataset[,!drop]

drop <- names(dataset) %in% c("diametro_tronco")
dataset <- dataset[,!drop]

drop <- names(dataset) %in% c("altura")
dataset <- dataset[,!drop]


drop <- names(testset) %in% c("ultima_modificacion")
testset <- testset[,!drop]

drop <- names(testset) %in% c("lat")
testset <- testset[,!drop]

drop <- names(testset) %in% c("long")
testset <- testset[,!drop]

drop <- names(testset) %in% c("nombre_seccion")
testset <- testset[,!drop]

drop <- names(testset) %in% c("seccion")
testset <- testset[,!drop]

drop <- names(testset) %in% c("diametro_tronco")
testset <- testset[,!drop]

drop <- names(testset) %in% c("altura")
testset <- testset[,!drop]


#testset$inclinacion_peligrosa <- as.factor(0)
#testset
#dataset
#positives <- dataset %>% filter(inclinacion_peligrosa == 1)
#negatives <- dataset %>% filter(inclinacion_peligrosa == 0)
# Take some random negatives for sample
#splitted <- sample(1:nrow(negatives),replace = F, size = 3800)
#negatives <- negatives[ splitted, ]
#dataset <- rbind(negatives,positives)
#dataset
#testset <- testset %>% mutate(inclinacion_peligrosa = as.factor(0))
#trainData$especie <- as.factor(trainData$especie)
#dataset
#testset$especie <- as.factor(testset$especie)
# Train model
#testset
rf <- randomForest(inclinacion_peligrosa ~ especie + circ_tronco_cm + area_seccion, data=dataset, importance=TRUE, ntree=500, mtry=2)
rf
inclinacion_peligrosa <- predict(rf, newdata = testset)
print(rf)
importance(rf)
# Formatting
inclinacion_peligrosa <- as.numeric(as.character(inclinacion_peligrosa))
id <- treesID
results <- data.frame(id,inclinacion_peligrosa)
results
data.frame(testset$id,testset$inclinacion_peligrosa) 
```
```{r}
#codigo agus
arbolado_train <-read_csv("arbolado-mza-dataset.csv")
arbolado_test <-read_csv("arbolado-mza-dataset-test.csv")

arbolado_train<-arbolado_train %>% mutate(inclinacion_peligrosa=ifelse(inclinacion_peligrosa=='1','si','no'))

arbolado_train$inclinacion_peligrosa <-as.factor(arbolado_train$inclinacion_peligrosa)

arbolado_train %>%  group_by(inclinacion_peligrosa) %>% summarise(total=n())

arbolado_train <- arbolado_train %>% mutate(circ_tronco_cm_cat= ifelse(`circ_tronco_cm`<=100,'bajo',
                                                                         ifelse(`circ_tronco_cm`>100 & `circ_tronco_cm` <= 200, 'medio',
                                                                                ifelse(`circ_tronco_cm` > 200 & `circ_tronco_cm` <= 300, 'alto','muy alto'))))
arbolado_test <- arbolado_test %>% mutate(circ_tronco_cm_cat= ifelse(`circ_tronco_cm`<=100,'bajo',
                                                                       ifelse(`circ_tronco_cm`>100 & `circ_tronco_cm` <= 200, 'medio',
                                                                              ifelse(`circ_tronco_cm` > 200 & `circ_tronco_cm` <= 300, 'alto','muy alto'))))




data_train_down<-downSample(arbolado_train,arbolado_train$inclinacion_peligrosa)
data_train_down %>%group_by(inclinacion_peligrosa) %>% summarise(total=n())


set.seed(950)

summary(data_train_down)
sapply(data_train_down, class)

summary(arbolado_test)
sapply(arbolado_test, class)

mod <- randomForest(inclinacion_peligrosa ~ altura+especie+diametro_tronco+circ_tronco_cm_cat,data = data_train_down,importance=TRUE,ntree = 500)
mod


pred <- predict(mod,arbolado_test)
pred
head(pred)

preds_tree<-ifelse(pred[,2] >=0.4,1,0)
submission<-data.frame(id=arbolado_test$id,inclinacion_peligrosa=pred)
readr::write_csv(submission,"resultsfinal.csv")
results <- read_csv("C:/Users/Agustina/Documents/results.csv")
results<- results %>% mutate(inclinacion_peligrosa=ifelse(inclinacion_peligrosa=='si','1','0'))
readr::write_csv(results,"resultsfinal.csv")
mod

```


```{r}
#codigo juanma
library(dplyr) 
library(readr)
library(rpart)
library(randomForest)
# Load dataset 
set.seed(123)
treesDataset <- read_csv("arbolado-mza-dataset.csv")
treesTestSet <- read_csv("arbolado-mza-dataset-test.csv")
treesDataset$inclinacion_peligrosa <- as.factor(treesDataset$inclinacion_peligrosa)
trainIndex <- createDataPartition(as.factor(treesDataset$inclinacion_peligrosa),p=0.80,list=FALSE)
trainData <- treesDataset[ trainIndex, ]
testData <- treesDataset[ -trainIndex, ]
# Save trees ID
treesID <- treesTestSet$id
positives <- trainData %>% filter(inclinacion_peligrosa == 1)
negatives <- trainData %>% filter(inclinacion_peligrosa == 0)
# Take some random negatives for sample
splitted <- sample(1:nrow(negatives),replace = F, size = 4500)
negatives <- negatives[ splitted, ]
trainData <- rbind(negatives,positives)
# Train model
rf <- randomForest(inclinacion_peligrosa ~ altura + especie + diametro_tronco,data=trainData, importance=TRUE, ntree=600, mtry=2)
inclinacion_peligrosa <- predict(rf, newdata=treesTestSet)
print(rf)
importance(rf)
# Formatting
inclinacion_peligrosa <- as.numeric(as.character(inclinacion_peligrosa))
id <- treesID
results <- data.frame(id,inclinacion_peligrosa)
results


```


